"""Terminal presentation. ASCII-safe by default."""
from ouro_agent.tui.screens import (
    render_battle_report,
    render_battle_screen,
    render_config_screen,
    render_codex_card,
    render_codex_summary,
    render_death_history,
    render_encounter_briefing,
    render_event,
    render_hero_card,
    render_hero_list,
    render_main_menu,
    render_progress_status,
    render_prompt_templates,
    render_run_setup_screen,
    render_rest,
    render_route_choice,
    render_reward_choice,
    render_shop,
    render_start_screen,
    render_run_archives,
    render_run_report,
    render_run_summary,
)
from ouro_agent.tui.terminal import Terminal, get_terminal
from ouro_agent.tui.frame_builder import BattleFrame, build_battle_frame
from ouro_agent.tui.presenter import (
    BattleScreenModel,
    battle_screen_model_from_frame,
    present_battle_screen_model,
)

__all__ = [
    "BattleFrame",
    "BattleScreenModel",
    "battle_screen_model_from_frame",
    "build_battle_frame",
    "present_battle_screen_model",
    "render_battle_report",
    "render_battle_screen",
    "render_codex_card",
    "render_codex_summary",
    "render_config_screen",
    "render_death_history",
    "render_encounter_briefing",
    "render_event",
    "render_hero_card",
    "render_hero_list",
    "render_main_menu",
    "render_progress_status",
    "render_prompt_templates",
    "render_run_setup_screen",
    "render_rest",
    "render_route_choice",
    "render_reward_choice",
    "render_shop",
    "render_start_screen",
    "render_run_archives",
    "render_run_report",
    "render_run_summary",
    "Terminal",
    "get_terminal",
]
